<?php

namespace App\Filament\Resources\TransactionChargesResource\Pages;

use App\Filament\Resources\TransactionChargesResource;
use Filament\Actions;
use Filament\Resources\Pages\ListRecords;

class ListTransactionCharges extends ListRecords
{
    protected static string $resource = TransactionChargesResource::class;

    protected function getHeaderActions(): array
    {
        return [
            // No create action needed for transaction charges as they are generated by the system
        ];
    }
}
